version: '3.3'
services:
  mysql_service:
    image: mysql:8.0.37
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=pin_services
      - MYSQL_USER=firstUser
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost"]

  app:
    build: .
    restart: always
    depends_on:
      - mysql_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.99.100:3306/pin_services?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"

volumes:
  dbdata:
